### ISSUE TITLE
"peur de", "envie de"

### ISSUE THREAD

**Issue by mmahamdi** [surfacesyntacticud/SUD_French-GSD#6]
Bonjour, 

Dans la construction "peur de", la relation entre "peur" et "de" est annotée de 3 manières différentes : udep, comp:obl et comp:obl@x alors qu'il n'y a pas de différence entre les occurrences. 
On a le même problème dans le French Spoken, avec udep et comp:obl.
Pour "envie de" , il n'y a qu'une seule relation dans le GSD , comp:obl@x. 
Dans French Spoken et Paris Stories, il y a différentes annotations. 

Si vous voulez, vous pouvez décider d'une relation définitive pour "peur de" (la même que pour "envie de", j'imagine) et on l'appliquera à French Spoken et Paris Stories. 

Bonne journée !

**Comment by bguil** [comment]
Je pense que c'est normal d'avoir différentes annotations à cause des verbes support ([light verb constructions](https://surfacesyntacticud.github.io/guidelines/u/particular_phenomena/lvc/)):

 * *la peur du noir* --> `udep` (pas de verbe support)
 * *j'ai peur du noir* --> `comp:obl` (avec verbe support)
 * *j'ai peur de tomber* --> `comp:obl@x` (avec verbe support et contrôle du sujet)

avec envie c'est pareil avec un exemple en plus:

 * *un patron très impliqué qui donne envie de goûter tous les plats* --> `comp:obl` car il y a un verbe support *donner*  mais pas `comp:obl@x` car le "sujet" de *goûter* n'est pas exprimé dans la phrase. 

J'ai vérifié dans GSD mais pas dans Spoken.

**Comment by sylvainkahane** [comment]
Oui les annotations de GSD sont conformes au guide (bien que le fait que le complément soit udep en cas d'absence d'un verbe soit un choix pas très satisfaisant mais plus ou moins imposé par UD).
J'ai regardé dans Spoken et deux cas de udep avec "avoir peur" sont à corriger : avoir -comp:obj@lvc-> peur -comp:obl-> de si le complément de peur est un nom et avoir -comp:obj@lvc-> peur -comp:obl@x-> de si c'est un verbe.
Menel, regarde les 63 occurrences de http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=6102a3bf4fbe6
Toutes celles avec des noms prédicatifs (envie, intention, soucis, etc.) sont à corriger.
Et aussi ces deux là avec faire : http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=6102a4a543a38
et celle-là avec prendre: http://match.grew.fr/?corpus=SUD_French-Spoken@latest&custom=6102a527c25ea

**Comment by sylvainkahane** [comment]
Du coup j'ai regardé les verbes supports dans GSD : http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=6102a587bda97&clustering=GOV.lemma
Je pense que les exemples suivants ne sont pas des LVC :

- pouvoir donner
- tenir compte est plutôt un idiom. D'ailleurs le complément des différents exemples a été traité à juste titre comme un complément du verbe. (Il y a un LVC qui est "tenir le compte (de ses médailles)"). Idem pour tenir lieu.
- tenir tête et tenir parole aussi
- mettre fin à qqch : je pense aussi. Le complément en à, analysé comme un udep, à corriger dans le premier exemple
- rendre compte est aussi un idom à mon avis. D'aillerus comme pour tenir compte, le complément a été traité à juste titre comme un complément du verbe.
- donner lieu : idem
- donner raison, donner naissance, donner lieu sont plutôt des idioms

Les LVC acceptent une modification du nom (avoir une grande envie, une ferme intention, un besoin immédiat, etc., rendre un bel hommage, etc.) et le nom peut s'employer sans le verbe ou avec un autre verbe.

**Comment by perrier54** [comment]
Je n'avais pas fait attention à cette différence entre idiomes et verbes supports mais je vais corriger French-GSD.

**Comment by mmahamdi** [comment]
désolée de la réponse tardive et merci pour tous ces éclaircissements, 
Vanessa a encore le fichier dev donc je la laisse terminer,  mais je me suis occupée du train et du test. 
J'ai quand même des petites hésitations pour ces constructions  : 
- avoir le droit de
- avoir les moyens de
- avoir la passion de la musique

**Comment by sylvainkahane** [comment]
avoir le droit de : LVC (le droit de se garer lui a été octroyé)

avoir les moyens de : LVC il n'a aucun moyen de faire ça

avoir la passion de la musique : "la passion de la musique" est l'objet de avoir et donc "de la musique" est udep de passion

**Comment by mmahamdi** [comment]
merci!

**Comment by perrier54** [comment]
J'ai corrigé le corpus [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD) et j'ai transformé les expressions avec verbes supports suivantes en expressions idiomatiques : 
perdre pied, prêter main forte, tenir compte|lieu, mettre fin, se rendre compte, donner lieu|raison|naissance|corps, prendre garde, avoir lieu|raison|gain de cause, faire face|fortune|grâce|partie|part|preuve|suite|loi|place|office|date|attention|équipe|débat|défaut
Je ne l'ai pas fait pour "rendre compte" car on peut dire "rendre un compte précis de ..."
