### ISSUE TITLE
Gender feature sur les DET féminins mais pas masculins et pluriel

### ISSUE THREAD

**Issue by mmahamdi** [surfacesyntacticud/SUD_French-GSD#8]
Bonjour, 

Est-il normal que les determinants possessifs masculins et/ou pluriels n'aient pas de trait Gender , mais que les féminins, si ? 
ex : 
sent_id = fr-ud-dev_00010
16	son	son	DET	_	**Number=Sing|Number[psor]=Sing|Person[psor]=3|PronType=Prs**	17	det	_	_
17	soutien	soutien	NOUN	_	Gender=Masc|Number=Sing	14	comp:obj	_	_

sent_id = fr-ud-dev_00015
4	sa	son	DET	_	**Gender=Fem|Number=Sing|Number[psor]=Sing|Person[psor]=3|PronType=Prs**	5	det	_	_
5	liste	liste	NOUN	_	Gender=Fem|Number=Sing	3	comp:obj	_

**Comment by perrier54** [comment]
Si je me souviens bien de la règle utilisée pour les déterminants, on met un genre quand la forme du déterminant détermine ce genre (_ma, ta, sa, la..._) mais ce n'est pas vrai pour _mon, ton , son, mes.._. (_mon amie_).

**Comment by mmahamdi** [comment]
d'accord, merci !

**Comment by sylvainkahane** [comment]
Ca me parait quand même bizarre que dans "son soutien", "son" ne soit pas Gender=Masc. C'est seulement devant voyelle que "son" n'est pas marqué en genre.
C'est différent pour "ses" qui n'est jamais marqué en genre.
