### ISSUE TITLE
fautes d'accord et de temps

### ISSUE THREAD

**Issue by mmahamdi** [surfacesyntacticud/SUD_French-GSD#9]
fr-ud-train_09050
Les alliés comptent 158 morts et 320 **blessé** et ont perdu 2 navires.

fr-ud-train_02371
Bieber ajoute « As long you love me/ I'll be your platinum/ I'll be your silver/ I'll be your gold », ce qui signifie en français « Aussi longtemps que tu m'aimes / Je **serais** ton platine / Je **serais** ton argent / Je **serais** ton or ».

**Comment by perrier54** [comment]
Pour le premier exemple, un trait _Typo=Yes_ indique l'erreur et la correction est donnée par _wordform=blessés_. Je viens de corriger le second exemple.

**Comment by mmahamdi** [comment]
merci!
